#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
DOTS_DIR="${DOTS_DIR:-$SCRIPT_DIR}"
CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"
BIN_HOME="${HOME}/.local/bin"
MODE="interactive"
FORCE=0
INSTALL_THEME_MANAGER=0
COMPONENTS=()

usage() {
    cat <<'EOF'
Usage: ./setup.sh [options] [components...]

Options:
  --all             Install every dotfile component without prompts.
  --force           Replace existing non-matching targets instead of skipping.
  --theme-manager   Build and install theme-set/theme-daemon to ~/.local/bin.
  --no-prompts      Only install components explicitly listed on the command line.
  -h, --help        Show this help.

Components:
  hypr ghostty nvim fish vicinae vicinae-themes lsd swaync zathura scripts firefox-colors

Examples:
  ./setup.sh --all --theme-manager
  ./setup.sh --all --force --theme-manager
  ./setup.sh fish nvim ghostty
EOF
}

log() { printf '==> %s\n' "$*"; }
warn() { printf 'WARN: %s\n' "$*" >&2; }

ask() {
    local prompt="$1"
    read -r -p "$prompt [y/N]: " ans
    [[ "$ans" =~ ^[Yy]$ ]]
}

contains_component() {
    local wanted="$1"
    local item
    for item in "${COMPONENTS[@]}"; do
        [[ "$item" == "$wanted" ]] && return 0
    done
    return 1
}

should_install() {
    local component="$1"
    case "$MODE" in
        all) return 0 ;;
        explicit) contains_component "$component" ;;
        interactive) ask "Setup ${component}?" ;;
    esac
}

replace_path() {
    local target="$1"
    if [[ "$FORCE" -eq 1 ]]; then
        rm -rf -- "$target"
        return 0
    fi
    warn "$target already exists and is not managed by this repo; skipping (use --force to replace)."
    return 1
}

link_target() {
    local target="$1"
    local source="$2"
    local name="$3"

    mkdir -p -- "$(dirname -- "$target")"

    if [[ -L "$target" ]]; then
        local current
        current="$(readlink -- "$target")"
        if [[ "$current" == "$source" ]]; then
            log "$name already linked."
            return 0
        fi
        replace_path "$target" || return 0
    elif [[ -e "$target" ]]; then
        replace_path "$target" || return 0
    fi

    ln -sfn -- "$source" "$target"
    log "Linked $name -> $target"
}

clone_or_update() {
    local url="$1"
    local target="$2"
    local name="$3"

    if [[ -d "$target/.git" ]]; then
        log "Updating $name..."
        git -C "$target" pull --ff-only
    elif [[ -e "$target" || -L "$target" ]]; then
        replace_path "$target" || return 0
        git clone "$url" "$target"
    else
        git clone "$url" "$target"
    fi
}

register_repo_path() {
    mkdir -p -- "$CONFIG_HOME/dots" "$STATE_HOME/theme" "$BIN_HOME"
    printf '%s\n' "$DOTS_DIR" > "$CONFIG_HOME/dots/path"
    cat > "$CONFIG_HOME/dots/env.fish" <<EOF
# Generated by dots/setup.sh. Do not edit manually.
set -gx DOTS_DIR '$DOTS_DIR'
EOF
    log "Registered DOTS_DIR=$DOTS_DIR"
}

install_theme_manager() {
    if ! command -v cargo >/dev/null 2>&1; then
        warn "cargo is not installed; skipping theme manager build."
        return 0
    fi

    log "Building theme manager..."
    cargo build --release --manifest-path "$DOTS_DIR/themes/theme_manager/Cargo.toml"
    install -Dm755 "$DOTS_DIR/themes/theme_manager/target/release/theme-set" "$BIN_HOME/theme-set"
    install -Dm755 "$DOTS_DIR/themes/theme_manager/target/release/theme-daemon" "$BIN_HOME/theme-daemon"
    log "Installed theme-set and theme-daemon to $BIN_HOME"
}

for arg in "$@"; do
    case "$arg" in
        --all|init)
            MODE="all"
            ;;
        --force|-f)
            FORCE=1
            ;;
        --theme-manager)
            INSTALL_THEME_MANAGER=1
            ;;
        --no-prompts)
            MODE="explicit"
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            COMPONENTS+=("$arg")
            [[ "$MODE" == "interactive" ]] && MODE="explicit"
            ;;
    esac
done

register_repo_path

should_install hypr && link_target "$CONFIG_HOME/hypr" "$DOTS_DIR/hypr" "Hyprland"
should_install ghostty && link_target "$CONFIG_HOME/ghostty" "$DOTS_DIR/ghostty" "Ghostty"
should_install nvim && link_target "$CONFIG_HOME/nvim" "$DOTS_DIR/nvim-perf" "Neovim"
should_install fish && link_target "$CONFIG_HOME/fish/config.fish" "$DOTS_DIR/modules/config.fish" "fish"
should_install vicinae && link_target "$CONFIG_HOME/vicinae" "$DOTS_DIR/vicinae" "Vicinae"
should_install vicinae-themes && link_target "$DATA_HOME/vicinae/themes" "$DOTS_DIR/vicinae-themes" "Vicinae themes"
should_install lsd && link_target "$CONFIG_HOME/lsd" "$DOTS_DIR/lsd" "lsd"
should_install swaync && link_target "$CONFIG_HOME/swaync" "$DOTS_DIR/swaync" "swaync"
should_install zathura && link_target "$CONFIG_HOME/zathura" "$DOTS_DIR/zathura" "zathura"
should_install firefox-colors && link_target "$CONFIG_HOME/firefox-colors" "$DOTS_DIR/firefox-colors" "Firefox colors"
should_install scripts && clone_or_update "https://github.com/adrsha/scripts" "$HOME/Scripts" "Scripts"

if [[ "$INSTALL_THEME_MANAGER" -eq 1 ]] || { [[ "$MODE" == "interactive" ]] && ask "Install theme manager binaries?"; }; then
    install_theme_manager
fi

if grep -qi "nixos" /etc/os-release 2>/dev/null; then
    log "NixOS detected. Keep hardware-configuration.nix machine-specific; copy it manually only when rebuilding this host."
fi

log "Done. Re-run safely any time; use --all for a full bootstrap and --force to replace existing unmanaged targets."
