-- Generated by theme-manager -- do not edit manually.

hl.config({
	general = {
		border_size = 0,
		col = {
			active_border = "rgb(37342F)",
			inactive_border = "rgb(37342F)",
		},
	},
	decoration = {
		rounding = 20,
	},
	misc = {
		background_color = "rgb(010101)",
	},
})
