#!/usr/bin/env fish
# _hyprland.fish — write Hyprland Lua colour config.

set -l border     (string replace '#' '' (get_theme_val BASE02))
set -l background (string replace '#' '' (get_theme_val DARKER_BLACK))

printf '%s\n' \
    "-- Generated by set_theme.fish -- do not edit manually." \
    "" \
    "hl.config({" \
    "    general = {" \
    "        col = {" \
    "            active_border = \"rgb($border)\"," \
    "            inactive_border = \"rgb($border)\"," \
    "        }," \
    "    }," \
    "    misc = {" \
    "        background_color = \"rgb($background)\"," \
    "    }," \
    "})" \
    > ~/dots/hypr/colors.lua
